package IDL.common.game_logic;


import IDL.common.referenceClasses.Player;

/**
* common/game_logic/GameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

public interface GameOperations 
{
  void sendLetter (char letter);
  void endLobby ();
  void sendTime (Player player);
} // interface GameOperations
