package common.referenceClasses;


/**
* common/referenceClasses/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public final class Admin implements org.omg.CORBA.portable.IDLEntity
{
  public int adminId = (int)0;
  public String username = null;
  public String password = null;

  public Admin ()
  {
  } // ctor

  public Admin (int _adminId, String _username, String _password)
  {
    adminId = _adminId;
    username = _username;
    password = _password;
  } // ctor

} // class Admin
