package common.referenceClasses;

/**
* common/referenceClasses/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public common.referenceClasses.Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (common.referenceClasses.Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.referenceClasses.AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.referenceClasses.AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.referenceClasses.AdminHelper.type ();
  }

}
