package common.referenceClasses;


/**
* common/referenceClasses/GameLobby.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public final class GameLobby implements org.omg.CORBA.portable.IDLEntity
{
  public int gameId = (int)0;
  public common.referenceClasses.Player players[] = null;
  public int waitingTime = (int)0;
  public int gameTime = (int)0;
  public String word = null;
  public common.referenceClasses.Player winner = null;

  public GameLobby ()
  {
  } // ctor

  public GameLobby (int _gameId, common.referenceClasses.Player[] _players, int _waitingTime, int _gameTime, String _word, common.referenceClasses.Player _winner)
  {
    gameId = _gameId;
    players = _players;
    waitingTime = _waitingTime;
    gameTime = _gameTime;
    word = _word;
    winner = _winner;
  } // ctor

} // class GameLobby
