package common.referenceClasses;

/**
* common/referenceClasses/GameLobbyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public final class GameLobbyHolder implements org.omg.CORBA.portable.Streamable
{
  public common.referenceClasses.GameLobby value = null;

  public GameLobbyHolder ()
  {
  }

  public GameLobbyHolder (common.referenceClasses.GameLobby initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.referenceClasses.GameLobbyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.referenceClasses.GameLobbyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.referenceClasses.GameLobbyHelper.type ();
  }

}
