package common.referenceClasses;

/**
* common/referenceClasses/LeaderboardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

public final class LeaderboardHolder implements org.omg.CORBA.portable.Streamable
{
  public common.referenceClasses.Leaderboard value = null;

  public LeaderboardHolder ()
  {
  }

  public LeaderboardHolder (common.referenceClasses.Leaderboard initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.referenceClasses.LeaderboardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.referenceClasses.LeaderboardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.referenceClasses.LeaderboardHelper.type ();
  }

}
