package common.referenceClasses;


/**
* common/referenceClasses/LeaderboardHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

abstract public class LeaderboardHelper
{
  private static String  _id = "IDL:common/referenceClasses/Leaderboard:1.0";

  public static void insert (org.omg.CORBA.Any a, common.referenceClasses.Leaderboard that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static common.referenceClasses.Leaderboard extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [1];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = common.referenceClasses.PlayerHelper.type ();
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_sequence_tc (0, _tcOf_members0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "player",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (common.referenceClasses.LeaderboardHelper.id (), "Leaderboard", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static common.referenceClasses.Leaderboard read (org.omg.CORBA.portable.InputStream istream)
  {
    common.referenceClasses.Leaderboard value = new common.referenceClasses.Leaderboard ();
    int _len0 = istream.read_long ();
    value.player = new common.referenceClasses.Player[_len0];
    for (int _o1 = 0;_o1 < value.player.length; ++_o1)
      value.player[_o1] = common.referenceClasses.PlayerHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, common.referenceClasses.Leaderboard value)
  {
    ostream.write_long (value.player.length);
    for (int _i0 = 0;_i0 < value.player.length; ++_i0)
      common.referenceClasses.PlayerHelper.write (ostream, value.player[_i0]);
  }

}
