package common.referenceClasses;


/**
* common/referenceClasses/Leaderboard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public final class Leaderboard implements org.omg.CORBA.portable.IDLEntity
{
  public common.referenceClasses.Player player[] = null;

  public Leaderboard ()
  {
  } // ctor

  public Leaderboard (common.referenceClasses.Player[] _player)
  {
    player = _player;
  } // ctor

} // class Leaderboard
