package common.referenceClasses;

/**
* common/referenceClasses/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public common.referenceClasses.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (common.referenceClasses.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.referenceClasses.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.referenceClasses.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.referenceClasses.PlayerHelper.type ();
  }

}
