package common.referenceClasses;


/**
* common/referenceClasses/ValuesList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public final class ValuesList implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CORBA.Any values[] = null;

  public ValuesList ()
  {
  } // ctor

  public ValuesList (org.omg.CORBA.Any[] _values)
  {
    values = _values;
  } // ctor

} // class ValuesList
