package Client.WhatsTheWord.game_logic;


import Client.WhatsTheWord.referenceClasses.Player;
import Client.WhatsTheWord.referenceClasses.PlayerHelper;

/**
* WhatsTheWord/game_logic/GamePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Monday, May 12, 2025 9:24:31 PM SGT
*/

public abstract class GamePOA extends org.omg.PortableServer.Servant
 implements GameOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendLetter", new Integer (0));
    _methods.put ("sendTime", new Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    Integer __method = (Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WhatsTheWord/game_logic/Game/sendLetter
       {
         char letter = in.read_char ();
         this.sendLetter (letter);
         out = $rh.createReply();
         break;
       }

       case 1:  // WhatsTheWord/game_logic/Game/sendTime
       {
         Player player = PlayerHelper.read (in);
         this.sendTime (player);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WhatsTheWord/game_logic/Game:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Game _this()
  {
    return GameHelper.narrow(
    super._this_object());
  }

  public Game _this(org.omg.CORBA.ORB orb)
  {
    return GameHelper.narrow(
    super._this_object(orb));
  }


} // class GamePOA
