package Client.WhatsTheWord.game_logic;


import Client.WhatsTheWord.referenceClasses.Player;

/**
* WhatsTheWord/game_logic/GameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

public interface GameOperations 
{
  void sendLetter (char letter);
  void endLobby ();
  void sendTime (Player player);
} // interface GameOperations
