package Client.WhatsTheWord.game_logic;


import Client.WhatsTheWord.referenceClasses.Player;

/**
* WhatsTheWord/game_logic/GameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public interface GameOperations 
{
  void sendLetter (char letter);
  void sendTime (Player player);
} // interface GameOperations
