package Client.WhatsTheWord.game_logic;

/**
* WhatsTheWord/game_logic/GameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public final class GameHolder implements org.omg.CORBA.portable.Streamable
{
  public Game value = null;

  public GameHolder ()
  {
  }

  public GameHolder (Game initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameHelper.type ();
  }

}
