package Server.WhatsTheWord.referenceClasses;


/**
* WhatsTheWord/referenceClasses/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

public final class Admin implements org.omg.CORBA.portable.IDLEntity
{
  public int adminId = (int)0;
  public String username = null;
  public String password = null;

  public Admin ()
  {
  } // ctor

  public Admin (int _adminId, String _username, String _password)
  {
    adminId = _adminId;
    username = _username;
    password = _password;
  } // ctor

} // class Admin
