package Server.WhatsTheWord.referenceClasses;

/**
* WhatsTheWord/referenceClasses/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminHelper.type ();
  }

}
