package Server.WhatsTheWord.referenceClasses;


/**
* WhatsTheWord/referenceClasses/GameLobby.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Monday, May 12, 2025 9:24:31 PM SGT
*/

public final class GameLobby implements org.omg.CORBA.portable.IDLEntity
{
  public int gameId = (int)0;
  public Player players[] = null;
  public int waitingTime = (int)0;
  public int gameTime = (int)0;
  public String word = null;
  public Player winner = null;

  public GameLobby ()
  {
  } // ctor

  public GameLobby (int _gameId, Player[] _players, int _waitingTime, int _gameTime, String _word, Player _winner)
  {
    gameId = _gameId;
    players = _players;
    waitingTime = _waitingTime;
    gameTime = _gameTime;
    word = _word;
    winner = _winner;
  } // ctor

} // class GameLobby
