package Server.WhatsTheWord.referenceClasses;

/**
* WhatsTheWord/referenceClasses/GameLobbyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public final class GameLobbyHolder implements org.omg.CORBA.portable.Streamable
{
  public GameLobby value = null;

  public GameLobbyHolder ()
  {
  }

  public GameLobbyHolder (GameLobby initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = GameLobbyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    GameLobbyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return GameLobbyHelper.type ();
  }

}
