package Server.WhatsTheWord.referenceClasses;


/**
* WhatsTheWord/referenceClasses/Leaderboard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public final class Leaderboard implements org.omg.CORBA.portable.IDLEntity
{
  public Player players[] = null;

  public Leaderboard ()
  {
  } // ctor

  public Leaderboard (Player[] _players)
  {
    players = _players;
  } // ctor

} // class Leaderboard
