package Server.WhatsTheWord.referenceClasses;

/**
* WhatsTheWord/referenceClasses/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerHelper.type ();
  }

}
