package Server.WhatsTheWord.referenceClasses;


/**
* WhatsTheWord/referenceClasses/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Monday, May 12, 2025 9:24:31 PM SGT
*/

public final class Player implements org.omg.CORBA.portable.IDLEntity
{
  public int playerId = (int)0;
  public String username = null;
  public String password = null;
  public int wins = (int)0;
  public int noOfRoundWins = (int)0;
  public int time = (int)0;
  public boolean hasPlayed = false;

  public Player ()
  {
  } // ctor

  public Player (int _playerId, String _username, String _password, int _wins, int _noOfRoundWins, int _time, boolean _hasPlayed)
  {
    playerId = _playerId;
    username = _username;
    password = _password;
    wins = _wins;
    noOfRoundWins = _noOfRoundWins;
    time = _time;
    hasPlayed = _hasPlayed;
  } // ctor

} // class Player
