package Server.WhatsTheWord.referenceClasses;


/**
* WhatsTheWord/referenceClasses/ValuesList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Monday, May 12, 2025 9:24:31 PM SGT
*/

public final class ValuesList implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CORBA.Any values[] = null;

  public ValuesList ()
  {
  } // ctor

  public ValuesList (org.omg.CORBA.Any[] _values)
  {
    values = _values;
  } // ctor

} // class ValuesList
