package Server.WhatsTheWord.referenceClasses;

/**
* WhatsTheWord/referenceClasses/ValuesListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public final class ValuesListHolder implements org.omg.CORBA.portable.Streamable
{
  public ValuesList value = null;

  public ValuesListHolder ()
  {
  }

  public ValuesListHolder (ValuesList initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ValuesListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ValuesListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ValuesListHelper.type ();
  }

}
