package Server.WhatsTheWord.game_logic;


/**
* WhatsTheWord/game_logic/Game.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Monday, May 12, 2025 9:24:31 PM SGT
*/

public interface Game extends GameOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Game
