package common.client.admin;

/**
* common/client/admin/AdminServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public final class AdminServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public common.client.admin.AdminService value = null;

  public AdminServiceHolder ()
  {
  }

  public AdminServiceHolder (common.client.admin.AdminService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.client.admin.AdminServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.client.admin.AdminServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.client.admin.AdminServiceHelper.type ();
  }

}
