package common.client.admin;


/**
* common/client/admin/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public interface AdminServiceOperations 
{
  void request (common.client.admin.AdminRequestType type, common.referenceClasses.Admin admin, common.client.ClientCallback adminCallback);
} // interface AdminServiceOperations
