package IDL.common.client.player;

/**
* common/client/player/PlayerRequestTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

public final class PlayerRequestTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public common.client.player.PlayerRequestType value = null;

  public PlayerRequestTypeHolder ()
  {
  }

  public PlayerRequestTypeHolder (common.client.player.PlayerRequestType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.client.player.PlayerRequestTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.client.player.PlayerRequestTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.client.player.PlayerRequestTypeHelper.type ();
  }

}
