package IDL.common.client.player;


/**
* common/client/player/PlayerRequestTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

abstract public class PlayerRequestTypeHelper
{
  private static String  _id = "IDL:common/client/player/PlayerRequestType:1.0";

  public static void insert (org.omg.CORBA.Any a, common.client.player.PlayerRequestType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static common.client.player.PlayerRequestType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (common.client.player.PlayerRequestTypeHelper.id (), "PlayerRequestType", new String[] { "REGISTER", "LOGIN", "START_GAME", "GET_LEADERBOARD"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static common.client.player.PlayerRequestType read (org.omg.CORBA.portable.InputStream istream)
  {
    return common.client.player.PlayerRequestType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, common.client.player.PlayerRequestType value)
  {
    ostream.write_long (value.value ());
  }

}
