package IDL.common.client.player;


import IDL.common.client.ClientCallback;
import IDL.common.referenceClasses.Player;

/**
* common/client/player/PlayerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

public interface PlayerServiceOperations 
{
  void request (common.client.player.PlayerRequestType type, Player player, ClientCallback playerCallback);
} // interface PlayerServiceOperations
