package CORBA_IDL.HelloApp;



/**
* HelloApp/Hello.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, April 6, 2025 6:41:48 PM SGT
*/

public interface Hello extends HelloApp.HelloOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface Hello
