package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Sunday, April 6, 2025 6:41:48 PM SGT
*/

public interface HelloOperations 
{
  String sayHello ();
} // interface HelloOperations
