package WhatsTheWord.client;


/**
* WhatsTheWord/client/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

public interface ClientCallbackOperations 
{
  void _notify (WhatsTheWord.referenceClasses.ValuesList list);
} // interface ClientCallbackOperations
