package WhatsTheWord.game_logic;


/**
* WhatsTheWord/game_logic/GameHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

abstract public class GameHelper
{
  private static String  _id = "IDL:WhatsTheWord/game_logic/Game:1.0";

  public static void insert (org.omg.CORBA.Any a, WhatsTheWord.game_logic.Game that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static WhatsTheWord.game_logic.Game extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (WhatsTheWord.game_logic.GameHelper.id (), "Game");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static WhatsTheWord.game_logic.Game read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_GameStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, WhatsTheWord.game_logic.Game value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static WhatsTheWord.game_logic.Game narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof WhatsTheWord.game_logic.Game)
      return (WhatsTheWord.game_logic.Game)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      WhatsTheWord.game_logic._GameStub stub = new WhatsTheWord.game_logic._GameStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static WhatsTheWord.game_logic.Game unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof WhatsTheWord.game_logic.Game)
      return (WhatsTheWord.game_logic.Game)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      WhatsTheWord.game_logic._GameStub stub = new WhatsTheWord.game_logic._GameStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
