package WhatsTheWord.game_logic;

/**
* WhatsTheWord/game_logic/GameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public final class GameHolder implements org.omg.CORBA.portable.Streamable
{
  public WhatsTheWord.game_logic.Game value = null;

  public GameHolder ()
  {
  }

  public GameHolder (WhatsTheWord.game_logic.Game initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WhatsTheWord.game_logic.GameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WhatsTheWord.game_logic.GameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WhatsTheWord.game_logic.GameHelper.type ();
  }

}
