package WhatsTheWord.game_logic;


/**
* WhatsTheWord/game_logic/GameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public interface GameOperations 
{
  void sendLetter (char letter);
  void endLobby ();
  void sendTime (WhatsTheWord.referenceClasses.Player player);
} // interface GameOperations
