package WhatsTheWord.client.player;


/**
* WhatsTheWord/client/player/PlayerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public interface PlayerServiceOperations 
{
  void request (WhatsTheWord.client.player.PlayerRequestType type, WhatsTheWord.referenceClasses.Player player, WhatsTheWord.client.ClientCallback playerCallback);
} // interface PlayerServiceOperations
