package WhatsTheWord.client.player;

/**
* WhatsTheWord/client/player/PlayerRequestTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

public final class PlayerRequestTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public WhatsTheWord.client.player.PlayerRequestType value = null;

  public PlayerRequestTypeHolder ()
  {
  }

  public PlayerRequestTypeHolder (WhatsTheWord.client.player.PlayerRequestType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WhatsTheWord.client.player.PlayerRequestTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WhatsTheWord.client.player.PlayerRequestTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WhatsTheWord.client.player.PlayerRequestTypeHelper.type ();
  }

}
