package WhatsTheWord.client.player;


/**
* WhatsTheWord/client/player/PlayerRequestType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public class PlayerRequestType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static WhatsTheWord.client.player.PlayerRequestType[] __array = new WhatsTheWord.client.player.PlayerRequestType [__size];

  public static final int _REGISTER = 0;
  public static final WhatsTheWord.client.player.PlayerRequestType REGISTER = new WhatsTheWord.client.player.PlayerRequestType(_REGISTER);
  public static final int _LOGIN = 1;
  public static final WhatsTheWord.client.player.PlayerRequestType LOGIN = new WhatsTheWord.client.player.PlayerRequestType(_LOGIN);
  public static final int _START_GAME = 2;
  public static final WhatsTheWord.client.player.PlayerRequestType START_GAME = new WhatsTheWord.client.player.PlayerRequestType(_START_GAME);
  public static final int _GET_LEADERBOARD = 3;
  public static final WhatsTheWord.client.player.PlayerRequestType GET_LEADERBOARD = new WhatsTheWord.client.player.PlayerRequestType(_GET_LEADERBOARD);

  public int value ()
  {
    return __value;
  }

  public static WhatsTheWord.client.player.PlayerRequestType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected PlayerRequestType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class PlayerRequestType
