package WhatsTheWord.client.player;


/**
* WhatsTheWord/client/player/PlayerServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public abstract class PlayerServicePOA extends org.omg.PortableServer.Servant
 implements WhatsTheWord.client.player.PlayerServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("request", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // WhatsTheWord/client/player/PlayerService/request
       {
         WhatsTheWord.client.player.PlayerRequestType type = WhatsTheWord.client.player.PlayerRequestTypeHelper.read (in);
         WhatsTheWord.referenceClasses.Player player = WhatsTheWord.referenceClasses.PlayerHelper.read (in);
         WhatsTheWord.client.ClientCallback playerCallback = WhatsTheWord.client.ClientCallbackHelper.read (in);
         this.request (type, player, playerCallback);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:WhatsTheWord/client/player/PlayerService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PlayerService _this() 
  {
    return PlayerServiceHelper.narrow(
    super._this_object());
  }

  public PlayerService _this(org.omg.CORBA.ORB orb) 
  {
    return PlayerServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PlayerServicePOA
