package WhatsTheWord.client.player;

/**
* WhatsTheWord/client/player/PlayerServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

public final class PlayerServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public WhatsTheWord.client.player.PlayerService value = null;

  public PlayerServiceHolder ()
  {
  }

  public PlayerServiceHolder (WhatsTheWord.client.player.PlayerService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WhatsTheWord.client.player.PlayerServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WhatsTheWord.client.player.PlayerServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WhatsTheWord.client.player.PlayerServiceHelper.type ();
  }

}
