package IDL.common.client.admin;


import IDL.common.client.ClientCallback;
import IDL.common.referenceClasses.Admin;

/**
* common/client/admin/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

public interface AdminServiceOperations 
{
  void request (common.client.admin.AdminRequestType type, Admin admin, ClientCallback adminCallback);
} // interface AdminServiceOperations
