package WhatsTheWord.referenceClasses;


/**
* WhatsTheWord/referenceClasses/AdminHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

abstract public class AdminHelper
{
  private static String  _id = "IDL:WhatsTheWord/referenceClasses/Admin:1.0";

  public static void insert (org.omg.CORBA.Any a, WhatsTheWord.referenceClasses.Admin that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static WhatsTheWord.referenceClasses.Admin extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [3];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "adminId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "username",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "password",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (WhatsTheWord.referenceClasses.AdminHelper.id (), "Admin", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static WhatsTheWord.referenceClasses.Admin read (org.omg.CORBA.portable.InputStream istream)
  {
    WhatsTheWord.referenceClasses.Admin value = new WhatsTheWord.referenceClasses.Admin ();
    value.adminId = istream.read_long ();
    value.username = istream.read_string ();
    value.password = istream.read_string ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, WhatsTheWord.referenceClasses.Admin value)
  {
    ostream.write_long (value.adminId);
    ostream.write_string (value.username);
    ostream.write_string (value.password);
  }

}
