package WhatsTheWord.referenceClasses;

/**
* WhatsTheWord/referenceClasses/AdminHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

public final class AdminHolder implements org.omg.CORBA.portable.Streamable
{
  public WhatsTheWord.referenceClasses.Admin value = null;

  public AdminHolder ()
  {
  }

  public AdminHolder (WhatsTheWord.referenceClasses.Admin initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WhatsTheWord.referenceClasses.AdminHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WhatsTheWord.referenceClasses.AdminHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WhatsTheWord.referenceClasses.AdminHelper.type ();
  }

}
