package WhatsTheWord.referenceClasses;

/**
* WhatsTheWord/referenceClasses/GameLobbyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

public final class GameLobbyHolder implements org.omg.CORBA.portable.Streamable
{
  public WhatsTheWord.referenceClasses.GameLobby value = null;

  public GameLobbyHolder ()
  {
  }

  public GameLobbyHolder (WhatsTheWord.referenceClasses.GameLobby initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WhatsTheWord.referenceClasses.GameLobbyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WhatsTheWord.referenceClasses.GameLobbyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WhatsTheWord.referenceClasses.GameLobbyHelper.type ();
  }

}
