package WhatsTheWord.referenceClasses;

/**
* WhatsTheWord/referenceClasses/LeaderboardHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public final class LeaderboardHolder implements org.omg.CORBA.portable.Streamable
{
  public WhatsTheWord.referenceClasses.Leaderboard value = null;

  public LeaderboardHolder ()
  {
  }

  public LeaderboardHolder (WhatsTheWord.referenceClasses.Leaderboard initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WhatsTheWord.referenceClasses.LeaderboardHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WhatsTheWord.referenceClasses.LeaderboardHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WhatsTheWord.referenceClasses.LeaderboardHelper.type ();
  }

}
