package WhatsTheWord.referenceClasses;


/**
* WhatsTheWord/referenceClasses/PlayerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

abstract public class PlayerHelper
{
  private static String  _id = "IDL:WhatsTheWord/referenceClasses/Player:1.0";

  public static void insert (org.omg.CORBA.Any a, WhatsTheWord.referenceClasses.Player that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static WhatsTheWord.referenceClasses.Player extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [7];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[0] = new org.omg.CORBA.StructMember (
            "playerId",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "username",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "password",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[3] = new org.omg.CORBA.StructMember (
            "wins",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "noOfRoundWins",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[5] = new org.omg.CORBA.StructMember (
            "time",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[6] = new org.omg.CORBA.StructMember (
            "hasPlayed",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (WhatsTheWord.referenceClasses.PlayerHelper.id (), "Player", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static WhatsTheWord.referenceClasses.Player read (org.omg.CORBA.portable.InputStream istream)
  {
    WhatsTheWord.referenceClasses.Player value = new WhatsTheWord.referenceClasses.Player ();
    value.playerId = istream.read_long ();
    value.username = istream.read_string ();
    value.password = istream.read_string ();
    value.wins = istream.read_long ();
    value.noOfRoundWins = istream.read_long ();
    value.time = istream.read_long ();
    value.hasPlayed = istream.read_boolean ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, WhatsTheWord.referenceClasses.Player value)
  {
    ostream.write_long (value.playerId);
    ostream.write_string (value.username);
    ostream.write_string (value.password);
    ostream.write_long (value.wins);
    ostream.write_long (value.noOfRoundWins);
    ostream.write_long (value.time);
    ostream.write_boolean (value.hasPlayed);
  }

}
