package WhatsTheWord.referenceClasses;

/**
* WhatsTheWord/referenceClasses/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public WhatsTheWord.referenceClasses.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (WhatsTheWord.referenceClasses.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WhatsTheWord.referenceClasses.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WhatsTheWord.referenceClasses.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WhatsTheWord.referenceClasses.PlayerHelper.type ();
  }

}
