package WhatsTheWord.referenceClasses;

/**
* WhatsTheWord/referenceClasses/ValuesListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public final class ValuesListHolder implements org.omg.CORBA.portable.Streamable
{
  public WhatsTheWord.referenceClasses.ValuesList value = null;

  public ValuesListHolder ()
  {
  }

  public ValuesListHolder (WhatsTheWord.referenceClasses.ValuesList initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WhatsTheWord.referenceClasses.ValuesListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WhatsTheWord.referenceClasses.ValuesListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WhatsTheWord.referenceClasses.ValuesListHelper.type ();
  }

}
