package Server.WhatsTheWord.client.admin;


/**
* WhatsTheWord/client/admin/AdminRequestType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Monday, May 12, 2025 9:24:31 PM SGT
*/

public class AdminRequestType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 8;
  private static AdminRequestType[] __array = new AdminRequestType[__size];

  public static final int _ADMIN_LOGIN = 0;
  public static final AdminRequestType ADMIN_LOGIN = new AdminRequestType(_ADMIN_LOGIN);
  public static final int _CREATE_NEW_PLAYER = 1;
  public static final AdminRequestType CREATE_NEW_PLAYER = new AdminRequestType(_CREATE_NEW_PLAYER);
  public static final int _GET_PLAYER_DETAILS = 2;
  public static final AdminRequestType GET_PLAYER_DETAILS = new AdminRequestType(_GET_PLAYER_DETAILS);
  public static final int _UPDATE_PLAYER_DETAILS = 3;
  public static final AdminRequestType UPDATE_PLAYER_DETAILS = new AdminRequestType(_UPDATE_PLAYER_DETAILS);
  public static final int _DELETE_PLAYER = 4;
  public static final AdminRequestType DELETE_PLAYER = new AdminRequestType(_DELETE_PLAYER);
  public static final int _SEARCH_PLAYER = 5;
  public static final AdminRequestType SEARCH_PLAYER = new AdminRequestType(_SEARCH_PLAYER);
  public static final int _SET_LOBBY_WAITING_TIME = 6;
  public static final AdminRequestType SET_LOBBY_WAITING_TIME = new AdminRequestType(_SET_LOBBY_WAITING_TIME);
  public static final int _SET_ROUND_TIME = 7;
  public static final AdminRequestType SET_ROUND_TIME = new AdminRequestType(_SET_ROUND_TIME);

  public int value ()
  {
    return __value;
  }

  public static AdminRequestType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AdminRequestType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AdminRequestType
