package Server.WhatsTheWord.client.admin;

/**
* WhatsTheWord/client/admin/AdminServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public final class AdminServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminService value = null;

  public AdminServiceHolder ()
  {
  }

  public AdminServiceHolder (AdminService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminServiceHelper.type ();
  }

}
