package Server.WhatsTheWord.client.admin;


import Server.WhatsTheWord.client.ClientCallback;
import Server.WhatsTheWord.referenceClasses.Admin;

/**
* WhatsTheWord/client/admin/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public interface AdminServiceOperations 
{
  void request (AdminRequestType type, Admin admin, ClientCallback adminCallback);
} // interface AdminServiceOperations
