package IDL.common.referenceClasses;


/**
* common/referenceClasses/ValuesList.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

public final class ValuesList implements org.omg.CORBA.portable.IDLEntity
{
  public org.omg.CORBA.Any values[] = null;

  public ValuesList ()
  {
  } // ctor

  public ValuesList (org.omg.CORBA.Any[] _values)
  {
    values = _values;
  } // ctor

} // class ValuesList
