package IDL.common.referenceClasses;

/**
* common/referenceClasses/ValuesListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

public final class ValuesListHolder implements org.omg.CORBA.portable.Streamable
{
  public common.referenceClasses.ValuesList value = null;

  public ValuesListHolder ()
  {
  }

  public ValuesListHolder (common.referenceClasses.ValuesList initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.referenceClasses.ValuesListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.referenceClasses.ValuesListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.referenceClasses.ValuesListHelper.type ();
  }

}
