package Client.WhatsTheWord.client;


import Client.WhatsTheWord.referenceClasses.ValuesList;

/**
* WhatsTheWord/client/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Monday, May 12, 2025 9:24:31 PM SGT
*/

public interface ClientCallbackOperations 
{
  void _notify (ValuesList list);
} // interface ClientCallbackOperations
