package Client.WhatsTheWord.client.admin;


import Client.WhatsTheWord.client.ClientCallback;
import Client.WhatsTheWord.referenceClasses.Admin;

/**
* WhatsTheWord/client/admin/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public interface AdminServiceOperations 
{
  void request (AdminRequestType type, Admin admin, ClientCallback adminCallback);
} // interface AdminServiceOperations
