package Client.WhatsTheWord.client.admin;


/**
* WhatsTheWord/client/admin/AdminService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Monday, May 12, 2025 9:24:31 PM SGT
*/

public interface AdminService extends AdminServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface AdminService
