package Client.WhatsTheWord.client.admin;

/**
* WhatsTheWord/client/admin/AdminRequestTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public final class AdminRequestTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public AdminRequestType value = null;

  public AdminRequestTypeHolder ()
  {
  }

  public AdminRequestTypeHolder (AdminRequestType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AdminRequestTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AdminRequestTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AdminRequestTypeHelper.type ();
  }

}
