package Client.WhatsTheWord.client.admin;


/**
* WhatsTheWord/client/admin/AdminRequestTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

abstract public class AdminRequestTypeHelper
{
  private static String  _id = "IDL:WhatsTheWord/client/admin/AdminRequestType:1.0";

  public static void insert (org.omg.CORBA.Any a, AdminRequestType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AdminRequestType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (AdminRequestTypeHelper.id (), "AdminRequestType", new String[] { "ADMIN_LOGIN", "CREATE_NEW_PLAYER", "GET_PLAYER_DETAILS", "UPDATE_PLAYER_DETAILS", "DELETE_PLAYER", "SEARCH_PLAYER", "SET_LOBBY_WAITING_TIME", "SET_ROUND_TIME"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AdminRequestType read (org.omg.CORBA.portable.InputStream istream)
  {
    return AdminRequestType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AdminRequestType value)
  {
    ostream.write_long (value.value ());
  }

}
