package Client.WhatsTheWord.client.player;

/**
* WhatsTheWord/client/player/PlayerRequestTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Monday, May 12, 2025 9:24:31 PM SGT
*/

public final class PlayerRequestTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public PlayerRequestType value = null;

  public PlayerRequestTypeHolder ()
  {
  }

  public PlayerRequestTypeHolder (PlayerRequestType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PlayerRequestTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PlayerRequestTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PlayerRequestTypeHelper.type ();
  }

}
