package Client.WhatsTheWord.client.player;


import Client.WhatsTheWord.client.ClientCallback;
import Client.WhatsTheWord.referenceClasses.Player;

/**
* WhatsTheWord/client/player/PlayerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public interface PlayerServiceOperations 
{
  void request (PlayerRequestType type, Player player, ClientCallback playerCallback);
} // interface PlayerServiceOperations
