package Client.WhatsTheWord.client.player;


/**
* WhatsTheWord/client/player/PlayerService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public interface PlayerService extends PlayerServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface PlayerService
