package common.client;


/**
* common/client/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

public interface ClientCallbackOperations 
{
  void _notify (common.referenceClasses.ValuesList list);
} // interface ClientCallbackOperations
