package common.client;


/**
* common/client/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public interface ClientCallbackOperations 
{
  void _notify (common.referenceClasses.ValuesList list);
} // interface ClientCallbackOperations
