package common.game_logic;


/**
* common/game_logic/GameOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public interface GameOperations 
{
  void sendLetter (char letter);
  void endLobby ();
  void sendTime (common.referenceClasses.Player player);
} // interface GameOperations
