package common.game_logic;


/**
* common/game_logic/GamePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public abstract class GamePOA extends org.omg.PortableServer.Servant
 implements common.game_logic.GameOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sendLetter", new java.lang.Integer (0));
    _methods.put ("endLobby", new java.lang.Integer (1));
    _methods.put ("sendTime", new java.lang.Integer (2));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // common/game_logic/Game/sendLetter
       {
         char letter = in.read_char ();
         this.sendLetter (letter);
         out = $rh.createReply();
         break;
       }

       case 1:  // common/game_logic/Game/endLobby
       {
         this.endLobby ();
         out = $rh.createReply();
         break;
       }

       case 2:  // common/game_logic/Game/sendTime
       {
         common.referenceClasses.Player player = common.referenceClasses.PlayerHelper.read (in);
         this.sendTime (player);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:common/game_logic/Game:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Game _this() 
  {
    return GameHelper.narrow(
    super._this_object());
  }

  public Game _this(org.omg.CORBA.ORB orb) 
  {
    return GameHelper.narrow(
    super._this_object(orb));
  }


} // class GamePOA
