package common.game_logic;

/**
* common/game_logic/GameHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public final class GameHolder implements org.omg.CORBA.portable.Streamable
{
  public common.game_logic.Game value = null;

  public GameHolder ()
  {
  }

  public GameHolder (common.game_logic.Game initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.game_logic.GameHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.game_logic.GameHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.game_logic.GameHelper.type ();
  }

}
