package Server.WhatsTheWord.client;


import Server.WhatsTheWord.referenceClasses.ValuesList;

/**
* WhatsTheWord/client/ClientCallbackOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public interface ClientCallbackOperations 
{
  void _notify (ValuesList list);
} // interface ClientCallbackOperations
