package Server.WhatsTheWord.client;


/**
* WhatsTheWord/client/ClientCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

public interface ClientCallback extends ClientCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity
{
} // interface ClientCallback
