package common.client.player;


/**
* common/client/player/PlayerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public interface PlayerServiceOperations 
{
  void request (common.client.player.PlayerRequestType type, common.referenceClasses.Player player, common.client.ClientCallback playerCallback);
} // interface PlayerServiceOperations
