package common.client.player;


/**
* common/client/player/PlayerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Wednesday, April 16, 2025 9:09:06 PM SGT
*/

public interface PlayerServiceOperations 
{
  void request (common.client.player.PlayerRequestType type, common.referenceClasses.Player player, common.client.ClientCallback playerCallback);
} // interface PlayerServiceOperations
