package common.client.player;


/**
* common/client/player/PlayerRequestType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public class PlayerRequestType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 4;
  private static common.client.player.PlayerRequestType[] __array = new common.client.player.PlayerRequestType [__size];

  public static final int _REGISTER = 0;
  public static final common.client.player.PlayerRequestType REGISTER = new common.client.player.PlayerRequestType(_REGISTER);
  public static final int _LOGIN = 1;
  public static final common.client.player.PlayerRequestType LOGIN = new common.client.player.PlayerRequestType(_LOGIN);
  public static final int _START_GAME = 2;
  public static final common.client.player.PlayerRequestType START_GAME = new common.client.player.PlayerRequestType(_START_GAME);
  public static final int _GET_LEADERBOARD = 3;
  public static final common.client.player.PlayerRequestType GET_LEADERBOARD = new common.client.player.PlayerRequestType(_GET_LEADERBOARD);

  public int value ()
  {
    return __value;
  }

  public static common.client.player.PlayerRequestType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected PlayerRequestType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class PlayerRequestType
