package common.client.player;

/**
* common/client/player/PlayerServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from CORBA.idl
* Friday, April 25, 2025 9:30:22 AM CST
*/

public final class PlayerServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public common.client.player.PlayerService value = null;

  public PlayerServiceHolder ()
  {
  }

  public PlayerServiceHolder (common.client.player.PlayerService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = common.client.player.PlayerServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    common.client.player.PlayerServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return common.client.player.PlayerServiceHelper.type ();
  }

}
