package Client.WhatsTheWord.referenceClasses;


/**
* WhatsTheWord/referenceClasses/Admin.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Thursday, May 15, 2025 6:17:05 PM SGT
*/

public final class Admin implements org.omg.CORBA.portable.IDLEntity
{
  public int adminId = (int)0;
  public String username = null;
  public String password = null;
  public int waitingTime = (int)0;
  public int gameTime = (int)0;

  public Admin ()
  {
  } // ctor

  public Admin (int _adminId, String _username, String _password, int _waitingTime, int _gameTime)
  {
    adminId = _adminId;
    username = _username;
    password = _password;
    waitingTime = _waitingTime;
    gameTime = _gameTime;
  } // ctor

} // class Admin
