package Client.WhatsTheWord.referenceClasses;


/**
* WhatsTheWord/referenceClasses/Leaderboard.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

public final class Leaderboard implements org.omg.CORBA.portable.IDLEntity
{
  public Player player[] = null;

  public Leaderboard ()
  {
  } // ctor

  public Leaderboard (Player[] _player)
  {
    player = _player;
  } // ctor

} // class Leaderboard
