package Server.WhatsTheWord.client.player;


/**
* WhatsTheWord/client/player/PlayerServiceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Sunday, April 27, 2025 8:25:28 PM SGT
*/

abstract public class PlayerServiceHelper
{
  private static String  _id = "IDL:WhatsTheWord/client/player/PlayerService:1.0";

  public static void insert (org.omg.CORBA.Any a, PlayerService that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PlayerService extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PlayerServiceHelper.id (), "PlayerService");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PlayerService read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_PlayerServiceStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PlayerService value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PlayerService narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PlayerService)
      return (PlayerService)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _PlayerServiceStub stub = new _PlayerServiceStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PlayerService unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PlayerService)
      return (PlayerService)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _PlayerServiceStub stub = new _PlayerServiceStub();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
