package Server.WhatsTheWord.client.player;


/**
* WhatsTheWord/client/player/PlayerRequestTypeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Monday, May 12, 2025 9:24:31 PM SGT
*/

abstract public class PlayerRequestTypeHelper
{
  private static String  _id = "IDL:WhatsTheWord/client/player/PlayerRequestType:1.0";

  public static void insert (org.omg.CORBA.Any a, PlayerRequestType that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PlayerRequestType extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (PlayerRequestTypeHelper.id (), "PlayerRequestType", new String[] { "REGISTER", "LOGIN", "START_GAME", "GET_LEADERBOARD", "LOGOUT"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PlayerRequestType read (org.omg.CORBA.portable.InputStream istream)
  {
    return PlayerRequestType.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PlayerRequestType value)
  {
    ostream.write_long (value.value ());
  }

}
