package Server.WhatsTheWord.client.player;


import Server.WhatsTheWord.client.ClientCallback;
import Server.WhatsTheWord.referenceClasses.Player;

/**
* WhatsTheWord/client/player/PlayerServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public interface PlayerServiceOperations 
{
  void request (PlayerRequestType type, Player player, ClientCallback playerCallback);
} // interface PlayerServiceOperations
