package WhatsTheWord.client.admin;


/**
* WhatsTheWord/client/admin/AdminRequestType.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public class AdminRequestType implements org.omg.CORBA.portable.IDLEntity
{
  private        int __value;
  private static int __size = 8;
  private static WhatsTheWord.client.admin.AdminRequestType[] __array = new WhatsTheWord.client.admin.AdminRequestType [__size];

  public static final int _ADMIN_LOGIN = 0;
  public static final WhatsTheWord.client.admin.AdminRequestType ADMIN_LOGIN = new WhatsTheWord.client.admin.AdminRequestType(_ADMIN_LOGIN);
  public static final int _CREATE_NEW_PLAYER = 1;
  public static final WhatsTheWord.client.admin.AdminRequestType CREATE_NEW_PLAYER = new WhatsTheWord.client.admin.AdminRequestType(_CREATE_NEW_PLAYER);
  public static final int _GET_PLAYER_DETAILS = 2;
  public static final WhatsTheWord.client.admin.AdminRequestType GET_PLAYER_DETAILS = new WhatsTheWord.client.admin.AdminRequestType(_GET_PLAYER_DETAILS);
  public static final int _UPDATE_PLAYER_DETAILS = 3;
  public static final WhatsTheWord.client.admin.AdminRequestType UPDATE_PLAYER_DETAILS = new WhatsTheWord.client.admin.AdminRequestType(_UPDATE_PLAYER_DETAILS);
  public static final int _DELETE_PLAYER = 4;
  public static final WhatsTheWord.client.admin.AdminRequestType DELETE_PLAYER = new WhatsTheWord.client.admin.AdminRequestType(_DELETE_PLAYER);
  public static final int _SEARCH_PLAYER = 5;
  public static final WhatsTheWord.client.admin.AdminRequestType SEARCH_PLAYER = new WhatsTheWord.client.admin.AdminRequestType(_SEARCH_PLAYER);
  public static final int _SET_LOBBY_WAITING_TIME = 6;
  public static final WhatsTheWord.client.admin.AdminRequestType SET_LOBBY_WAITING_TIME = new WhatsTheWord.client.admin.AdminRequestType(_SET_LOBBY_WAITING_TIME);
  public static final int _SET_ROUND_TIME = 7;
  public static final WhatsTheWord.client.admin.AdminRequestType SET_ROUND_TIME = new WhatsTheWord.client.admin.AdminRequestType(_SET_ROUND_TIME);

  public int value ()
  {
    return __value;
  }

  public static WhatsTheWord.client.admin.AdminRequestType from_int (int value)
  {
    if (value >= 0 && value < __size)
      return __array[value];
    else
      throw new org.omg.CORBA.BAD_PARAM ();
  }

  protected AdminRequestType (int value)
  {
    __value = value;
    __array[__value] = this;
  }
} // class AdminRequestType
