package WhatsTheWord.client.admin;

/**
* WhatsTheWord/client/admin/AdminRequestTypeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public final class AdminRequestTypeHolder implements org.omg.CORBA.portable.Streamable
{
  public WhatsTheWord.client.admin.AdminRequestType value = null;

  public AdminRequestTypeHolder ()
  {
  }

  public AdminRequestTypeHolder (WhatsTheWord.client.admin.AdminRequestType initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = WhatsTheWord.client.admin.AdminRequestTypeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    WhatsTheWord.client.admin.AdminRequestTypeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return WhatsTheWord.client.admin.AdminRequestTypeHelper.type ();
  }

}
