package WhatsTheWord.client.admin;


/**
* WhatsTheWord/client/admin/AdminServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from WhatsTheWord.idl
* Wednesday, April 30, 2025 8:13:25 PM SGT
*/

public interface AdminServiceOperations 
{
  void request (WhatsTheWord.client.admin.AdminRequestType type, WhatsTheWord.referenceClasses.Admin admin, WhatsTheWord.client.ClientCallback adminCallback);
} // interface AdminServiceOperations
